# Generated by Django 3.0.8 on 2020-07-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='inactive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
