# Generated by Django 3.0.8 on 2020-07-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_user', '0003_auto_20200719_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
