# Generated by Django 2.2.8 on 2021-04-13 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ins_user', '0006_auto_20210220_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_xid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
